from flask import Flask,render_template,url_for,flash,redirect
from forms import Registrationform,Loginform
app=Flask(__name__)
app.config["SECRET_KEY"]="872fa1955c0d33996a1f8172cf000e4f"             # here anything can be written , generally it is for security reasons
                                                                        # but random key can be generated by following command
                                                                        # python -> import secrets -> secrets.token_hex(16)
posts=[{
    "author":"ammar",
    "title":"blogpost1",
    "dateposted":"feb 2025"
},{
    "author":"mustafa",
    "title":"blogpost2",
    "dateposted":"mar 2025"
}]

@app.route("/")
@app.route("/home")
def home():
    return render_template('home.html',posts=posts)

@app.route("/about")
def about():
    return render_template('about.html',title="about")

@app.route("/register",methods=['GET','POST'])
def register():
    form=Registrationform()
    # if form.validate_on_submit():
    #     flash(f'Account created for {form.username.data}!',"success")
    #     return redirect(url_for("home"))
    return render_template("register.html",title="Register",form=form)

@app.route("/login")
def login():
    form=Loginform()
    return render_template("login.html",title="login",form=form)

if __name__=="__main__":
    app.run(debug=True)